openapi: "3.1.0"
info:
  title: "Admin API"
  description: "API for managing room bookings, including admin operations"
  version: "1.0.0"
servers:
  - url: "http://localhost:3001"
paths:
  /admins:
    post:
      summary: "Create a new admin"
      operationId: "createAdmin"
      tags:
        - "Admin"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Admin'
      responses:
        '201':
          description: "Admin created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
        '400':
          description: "Invalid input, object invalid"
        '409':
          description: "An existing item already exists"
    get:
      summary: "Get a list of all admins"
      operationId: "getAdmins"
      tags:
        - "Admin"
      responses:
        '200':
          description: "A list of Admins"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Admin'
        '404':
          description: "No admins found"
  /admins/{adminId}:
    get:
      summary: "Get a single admin by ID"
      operationId: "getAdminById"
      tags:
        - "Admin"
      parameters:
        - name: "adminId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        '200':
          description: "Admin profile information"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Admin'
        '404':
          description: "Admin not found"
    put:
      summary: "Update an existing admin"
      operationId: "updateAdmin"
      tags:
        - "Admin"
      parameters:
        - name: "adminId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Admin'
      responses:
        '200':
          description: "Admin updated successfully"
        '400':
          description: "Invalid input, object invalid"
        '404':
          description: "Admin not found"
    delete:
      summary: "Delete an admin"
      operationId: "deleteAdmin"
      tags:
        - "Admin"
      parameters:
        - name: "adminId"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        '204':
          description: "Admin deleted successfully"
        '400':
          description: "Invalid input, id invalid"
        '404':
          description: "Admin not found"
components:
  schemas:
    Admin:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
          readOnly: true
          description: "Unique identifier for the admin"
        name:
          type: "string"
        email:
          type: "string"
          format: "email"
        hashedPassword:
          type: "string"
          format: "password"
        salt:
          type: "string"
      required:
        - name
        - email
        - hashedPassword
        - salt
